"""
PDF Generation Engine for OmniNotes AI
Generates polished PDFs from formatted markdown text
"""

import os
import re
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor, black, grey
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, PageBreak,
        ListFlowable, ListItem, Table, TableStyle, KeepTogether
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_pdf(markdown_text: str, output_path: str, title: str = "OmniNotes AI"):
    """Generate a PDF from markdown-formatted text"""
    if not REPORTLAB_AVAILABLE:
        # Fallback: create a simple text PDF
        generate_simple_pdf(markdown_text, output_path, title)
        return

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72
    )

    # Custom styles
    styles = getSampleStyleSheet()

    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=HexColor('#1a1a2e'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )

    # Heading styles
    h1_style = ParagraphStyle(
        'CustomH1',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=HexColor('#16213e'),
        spaceAfter=12,
        spaceBefore=12,
        fontName='Helvetica-Bold',
        borderColor=HexColor('#e94560'),
        borderWidth=2,
        borderPadding=5,
        leftIndent=0,
        backColor=HexColor('#f8f9fa')
    )

    h2_style = ParagraphStyle(
        'CustomH2',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=HexColor('#0f3460'),
        spaceAfter=10,
        spaceBefore=10,
        fontName='Helvetica-Bold'
    )

    h3_style = ParagraphStyle(
        'CustomH3',
        parent=styles['Heading3'],
        fontSize=12,
        textColor=HexColor('#533483'),
        spaceAfter=8,
        spaceBefore=8,
        fontName='Helvetica-Bold'
    )

    # Body style
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['BodyText'],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
        spaceAfter=6
    )

    # Bullet style
    bullet_style = ParagraphStyle(
        'CustomBullet',
        parent=styles['BodyText'],
        fontSize=10,
        leading=14,
        leftIndent=20,
        spaceAfter=4,
        bulletIndent=10,
        bulletFontName='Helvetica-Bold',
        bulletColor=HexColor('#e94560')
    )

    # Code/equation style
    code_style = ParagraphStyle(
        'CustomCode',
        parent=styles['Code'],
        fontSize=9,
        leading=12,
        leftIndent=20,
        rightIndent=20,
        spaceAfter=6,
        backColor=HexColor('#f4f4f4'),
        borderColor=HexColor('#ddd'),
        borderWidth=1,
        borderPadding=8
    )

    story = []

    # Header
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(
        f"Generated by OmniNotes AI • {datetime.now().strftime('%B %d, %Y')}",
        ParagraphStyle('Subtitle', parent=styles['Normal'], fontSize=9, textColor=grey, alignment=TA_CENTER, spaceAfter=20)
    ))
    story.append(Spacer(1, 20))

    # Parse markdown and build PDF elements
    lines = markdown_text.split('\n')
    i = 0

    while i < len(lines):
        line = lines[i].strip()

        if not line:
            story.append(Spacer(1, 6))
            i += 1
            continue

        # Headers
        if line.startswith('# ') and not line.startswith('## '):
            story.append(Paragraph(line[2:], h1_style))
            i += 1
            continue

        if line.startswith('## ') and not line.startswith('### '):
            story.append(Paragraph(line[3:], h2_style))
            i += 1
            continue

        if line.startswith('### '):
            story.append(Paragraph(line[4:], h3_style))
            i += 1
            continue

        # Horizontal rule
        if line == '---' or line == '***':
            story.append(Spacer(1, 12))
            i += 1
            continue

        # Code blocks
        if line.startswith('```'):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('```'):
                code_lines.append(lines[i])
                i += 1
            code_text = escape_xml('\n'.join(code_lines)).replace('\n', '<br/>')
            story.append(Paragraph(f"<font face='Courier'>{code_text}</font>", code_style))
            i += 1
            continue

        # Inline code
        line = re.sub(r'`([^`]+)`', r'<font face="Courier" backColor="#f4f4f4">\1</font>', line)

        # Bold and italic
        line = re.sub(r'\*\*\*([^*]+)\*\*\*', r'<b><i>\1</i></b>', line)
        line = re.sub(r'\*\*([^*]+)\*\*', r'<b>\1</b>', line)
        line = re.sub(r'\*([^*]+)\*', r'<i>\1</i>', line)
        line = re.sub(r'__([^_]+)__', r'<b>\1</b>', line)
        line = re.sub(r'_([^_]+)_', r'<i>\1</i>', line)

        # Bullet points
        if line.startswith('- ') or line.startswith('* '):
            content = line[2:]
            content = escape_xml(content)
            story.append(Paragraph(f"• {content}", bullet_style))
            i += 1
            continue

        # Numbered lists
        num_match = re.match(r'^(\d+)[.\)]\s(.+)$', line)
        if num_match:
            num, content = num_match.groups()
            content = escape_xml(content)
            story.append(Paragraph(f"{num}. {content}", bullet_style))
            i += 1
            continue

        # Blockquotes
        if line.startswith('>'):
            content = line[1:].strip()
            content = escape_xml(content)
            quote_style = ParagraphStyle(
                'Quote', parent=body_style, leftIndent=30, 
                rightIndent=30, textColor=HexColor('#555'),
                fontName='Helvetica-Oblique'
            )
            story.append(Paragraph(content, quote_style))
            i += 1
            continue

        # Regular paragraph
        line = escape_xml(line)
        story.append(Paragraph(line, body_style))
        i += 1

    # Footer note
    story.append(Spacer(1, 30))
    story.append(Paragraph(
        "— Generated by OmniNotes AI —",
        ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=grey, alignment=TA_CENTER)
    ))

    doc.build(story)


def escape_xml(text: str) -> str:
    """Escape XML special characters for ReportLab"""
    text = text.replace('&', '&amp;')
    text = text.replace('<', '&lt;')
    text = text.replace('>', '&gt;')
    # Restore allowed HTML tags
    text = text.replace('&lt;b&gt;', '<b>')
    text = text.replace('&lt;/b&gt;', '</b>')
    text = text.replace('&lt;i&gt;', '<i>')
    text = text.replace('&lt;/i&gt;', '</i>')
    text = text.replace('&lt;font', '<font')
    text = text.replace('&lt;/font&gt;', '</font>')
    text = text.replace('&lt;br/&gt;', '<br/>')
    text = text.replace('&lt;br&gt;', '<br/>')
    return text


def generate_simple_pdf(text: str, output_path: str, title: str):
    """Fallback PDF generation without ReportLab styling"""
    try:
        from fpdf import FPDF

        class PDF(FPDF):
            def header(self):
                self.set_font('Arial', 'B', 16)
                self.cell(0, 10, title, 0, 1, 'C')
                self.ln(5)

            def footer(self):
                self.set_y(-15)
                self.set_font('Arial', 'I', 8)
                self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

        pdf = PDF()
        pdf.add_page()
        pdf.set_font('Arial', '', 11)

        for line in text.split('\n'):
            if line.startswith('# '):
                pdf.set_font('Arial', 'B', 14)
                pdf.cell(0, 10, line[2:], 0, 1)
                pdf.set_font('Arial', '', 11)
            elif line.startswith('## '):
                pdf.set_font('Arial', 'B', 12)
                pdf.cell(0, 8, line[3:], 0, 1)
                pdf.set_font('Arial', '', 11)
            else:
                pdf.multi_cell(0, 5, line)
            pdf.ln(2)

        pdf.output(output_path)
    except ImportError:
        # Last resort: plain text file
        with open(output_path.replace('.pdf', '.txt'), 'w') as f:
            f.write(text)
